name:
  zh: 张易成
  en: JOEYCH
role:
  zh: 电子信息工程本科毕业生
  en: Electronic & Information Engineering Graduate
favicon: favicon.svg
contact:
  email: szjoeych@gmail.com
  github: https://github.com/JOEYZYC
  scholar: https://scholar.google.com/citations?user=R_3hg2gAAAAJ
  orcid: https://orcid.org/0009-0009-0202-8772
